name: Daily Update

on:
  schedule:
    - cron: '0 0 * * *' # 한국 시간 매일 오전 9시
  workflow_dispatch: # 수동 실행 버튼 활성화

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4
      - name: Run scraper
        run: python scraper.py
      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add data.json
          git commit -m "Update daily bestseller data" || exit 0
          git push
